var artistArray = [

"*NSYNC",
"50 Cent",
"Adam Lambert",
"Adele",
"Aimee Mann",
"Alabama Shakes",
"Alanis Morissette",
"Alicia Keys",
"All-4-One",
"Amy Winehouse",
"Anderson .Paak",
"Andrea Bocelli",
"Arcade Fire",
"Ariana Grande",
"Ashanti",
"Avril Lavigne",
"B.o.B",
"Backstreet Boys",
"Barbra Streisand",
"Barenaked Ladies",
"Beastie Boys",
"Beck",
"Beyoncé",
"Blake Shelton",
"Bob Dylan",
"Bon Iver",
"Bon Jovi",
"Bonnie Raitt",
"Bowling for Soup",
"Boyz II Men",
"Brandy",
"Brandy Clark",
"Brandy, Monica",
"Brian McKnight",
"Brian Wilson",
"Britney Spears",
"Bruce Springsteen",
"Bruno Mars",
"Cam",
"Carly Rae Jepsen",
"Carrie Underwood",
"Cee Lo Green",
"Celine Dion",
"Chris Stapleton",
"Christina Aguilera",
"Colbie Caillat",
"Coldplay",
"Coolio",
"Corinne Bailey Rae",
"Courtney Barnett",
"Craig David",
"D'Angelo",
"Daft Punk",
"Daniel Powter",
"Daughtry",
"Dave Matthews Band",
"David Gray",
"Death Cab for Cutie",
"Demi Lovato",
"Destiny's Child",
"Dixie Chicks",
"Drake",
"Duffy",
"Eagle-Eye Cherry",
"Eagles",
"Ed Sheeran",
"Elton John",
"Elvis Costello",
"Eminem",
"Eric Church",
"Eric Clapton",
"Eric Clapton, Steve Winwood",
"Erykah Badu",
"Estelle",
"Evanescence",
"Feist",
"Fiona Apple",
"Five for Fighting",
"Fleetwood Mac",
"Florence and the Machine",
"Foo Fighters",
"Foster the People",
"Fountains of Wayne",
"Frank Ocean",
"Franz Ferdinand",
"Fun",
"Garbage",
"George Harrison",
"Glee Cast",
"Gloria Estefan",
"Gnarls Barkley",
"Goo Goo Dolls",
"Gorillaz",
"Gotye",
"Green Day",
"Gretchen Wilson",
"Hanson",
"Heather Headley",
"Herbie Hancock",
"Hootie & the Blowfish",
"Hozier",
"Hunter Hayes",
"Iggy Azalea",
"Imagine Dragons",
"Imogen Heap",
"India.Arie",
"J. Cole",
"Jack Johnson",
"Jack White",
"James Bay",
"James Blake",
"James Blunt",
"James Taylor",
"Jamiroquai",
"Jason Aldean",
"Jazmine Sullivan",
"Jewel",
"Joan Osborne",
"John Legend",
"John Mayer",
"John Mayer with Taylor Swift",
"Jonas Brothers",
"Joni Mitchell",
"Josh Groban",
"Joss Stone",
"Justin Bieber",
"Justin Timberlake",
"Kacey Musgraves",
"Kanye West",
"Katy Perry",
"Keane",
"Keith Urban",
"Kelly Clarkson",
"Kelsea Ballerini",
"Kendrick Lamar",
"Kid Rock",
"Kings of Leon",
"KT Tunstall",
"Lady Antebellum",
"Lady Gaga",
"Lauryn Hill",
"LeAnn Rimes",
"Lee Ann Womack",
"Leona Lewis",
"Lil Wayne",
"Little Big Town",
"Lorde",
"Los Lonely Boys",
"Lou Bega",
"Lukas Graham",
"Luther Vandross",
"M.I.A.",
"Macklemore",
"Macy Gray",
"Madonna",
"Marc Anthony",
"Maren Morris",
"Mariah Carey",
"Mark Ronson",
"Maroon 5",
"Mary Chapin Carpenter",
"Mary J. Blige",
"Matchbox Twenty",
"Meghan Trainor",
"Michael Bolton",
"Michael Bublé",
"Michael Jackson",
"Michael McDonald",
"Michelle Branch",
"Miguel",
"Miley Cyrus",
"Miranda Lambert",
"Missy Elliott",
"Mumford & Sons",
"Muse",
"Natalie Imbruglia",
"Natasha Bedingfield",
"Ne-Yo",
"Neil Young",
"Nelly",
"Nelly Furtado",
"Nickelback",
"Nicki Minaj",
"No Doubt",
"Norah Jones",
"OneRepublic",
"OutKast",
"Paramore",
"Paul McCartney",
"Paul Simon",
"Paula Cole",
"Pharrell Williams",
"Pink",
"Plain White T's",
"Prince",
"R. Kelly",
"R.E.M.",
"Radiohead",
"Rascal Flatts",
"Ray Charles",
"Ray LaMontagne",
"Red Hot Chili Peppers",
"Ricky Martin",
"Rihanna",
"Rob Thomas",
"Robert Plant",
"Robin Thicke",
"Sade",
"Sam Hunt",
"Sam Smith",
"Santana",
"Sara Bareilles",
"Seal",
"Sean Paul",
"Shania Twain",
"Shawn Colvin",
"Shawn Mullins",
"Sheryl Crow",
"Sia",
"Skrillex",
"Steely Dan",
"Stevie Wonder",
"Sting",
"Sturgill Simpson",
"Sugarland",
"Susan Tedeschi",
"Taylor Swift",
"The Band Perry",
"The Black Eyed Peas",
"The Black Keys",
"The Chainsmokers",
"The Corrs",
"The Fray",
"The Lumineers",
"The Pussycat Dolls",
"The Rolling Stones",
"The Smashing Pumpkins",
"The Soggy Bottom Boys",
"The Tony Rich Project",
"The Weeknd",
"The White Stripes",
"Thomas Rhett",
"Tim McGraw",
"TLC",
"Toni Braxton",
"Tony Bennett",
"Tori Kelly",
"Tracy Chapman",
"Train",
"Twenty One Pilots",
"U2",
"Usher",
"Vanessa Carlton",
"Vince Gill",
"Warren Zevon",
"Wiz Khalifa",
"Zac Brown Band"

]

var songArray = [

"'...Baby One More Time' by Britney Spears",
"'(You Want To) Make a Memory' by Bon Jovi",
"'1234' by Feist",
"'1979' by The Smashing Pumpkins",
"'21 Guns' by Green Day",
"'7 Days' by Craig David",
"'7 Years' by Lukas Graham",
"'A Sky Full of Stars' by Coldplay",
"'A Thousand Miles' by Vanessa Carlton",
"'Adorn' by Miguel",
"'Ain't No Mountain High Enough' by Michael McDonald",
"'Ain't No Other Man' by Christina Aguilera",
"'All About That Bass' by Meghan Trainor",
"'All I Wanna Do' by Sheryl Crow",
"'All of Me (Live)' by John Legend",
"'All You Wanted' by Michelle Branch",
"'Alright' by Kendrick Lamar",
"'Am I Wrong' by Anderson .Paak featuring Schoolboy Q",
"'American Boy' by Estelle featuring Kanye West",
"'American Idiot' by Green Day",
"'Amor Ti Vieta' by Andrea Bocelli",
"'Any Man of Mine' by Shania Twain",
"'Any Road' by George Harrison",
"'Anybody Seen My Baby?' by The Rolling Stones",
"'Anytime' by Brian McKnight",
"'Apologize' by OneRepublic",
"'Baby' by Brandy",
"'Babyfather' by Sade",
"'Babylon' by David Gray",
"'Bad Day' by Daniel Powter",
"'Bawitdaba' by Kid Rock",
"'Be Without You' by Mary J. Blige",
"'Beautiful Day' by U2",
"'Beautiful' by Christina Aguilera",
"'Because You Loved Me' by Celine Dion",
"'Before He Cheats' by Carrie Underwood",
"'Beg Steal or Borrow' by Ray LaMontagne and the Pariah Dogs",
"'Begin Again' by Taylor Swift",
"'Best of You' by Foo Fighters",
"'Black Horse and the Cherry Tree' by KT Tunstall",
"'Blank Space' by Taylor Swift",
"'Bleeding Love' by Leona Lewis",
"'Bless the Broken Road' by Rascal Flatts",
"'Blue Ain't Your Color' by Keith Urban",
"'Blue Moon' by Beck",
"'Blurred Lines' by Robin Thicke featuring T.I. and Pharrell Williams",
"'Body and Soul' by Tony Bennett & Amy Winehouse",
"'Both Sides Now' by Joni Mitchell",
"'Boulevard of Broken Dreams' by Green Day",
"'Brace for Impact (Live a Little)' by Sturgill Simpson",
"'Brand New Day' by Sting",
"'Brave' by Sara Bareilles",
"'Breathless' by The Corrs",
"'Burn' by Usher",
"'Burnin' Up' by Jonas Brothers featuring Big Rob",
"'Burning House' by Cam",
"'Bye Bye Bye' by *NSYNC",
"'California Gurls' by Katy Perry featuring Snoop Dogg",
"'Call Me Maybe' by Carly Rae Jepsen",
"'Can You Feel the Love Tonight' by Elton John",
"'Can't Feel My Face' by The Weeknd",
"'Can't Find My Way Home' by Eric Clapton, Steve Winwood",
"'Candyman' by Christina Aguilera",
"'Ch-Check It Out' by Beastie Boys",
"'Chances Are' by Lee Ann Womack",
"'Chandelier' by Sia",
"'Change the World' by Eric Clapton",
"'Charlie Brown' by Coldplay",
"'Chasing Pavements' by Adele",
"'Cheap Thrills' by Sia featuring Sean Paul",
"'Chicken Fried' by Zac Brown Band",
"'Church Bells' by Carrie Underwood",
"'Cinnamon Girl' by Prince",
"'City of Blinding Lights' by U2",
"'Clocks' by Coldplay",
"'Closer' by Ne-Yo",
"'Closer' by The Chainsmokers featuring Halsey",
"'Come Get It Bae' by Pharrell Williams",
"'Complicated' by Avril Lavigne",
"'Confident' by Demi Lovato",
"'Cousin Dupree' by Steely Dan",
"'Crazy in Love' by Beyoncé featuring Jay-Z",
"'Crazy' by Gnarls Barkley",
"'Criminal' by Fiona Apple",
"'Cry Me a River' by Justin Timberlake",
"'Dance Tonight' by Paul McCartney",
"'Dance with My Father' by Luther Vandross",
"'Dangerous Woman' by Ariana Grande",
"'Dani California' by Red Hot Chili Peppers",
"'Dark Horse' by Katy Perry featuring Juicy J",
"'Daughters' by John Mayer",
"'Day Drinking' by Little Big Town",
"'Dearest' by The Black Keys",
"'Devils & Dust' by Bruce Springsteen",
"'Die a Happy Man' by Thomas Rhett",
"'Do Something' by Macy Gray",
"'Do You Want To' by Franz Ferdinand",
"'Don't Hurt Yourself' by Beyoncé featuring Jack White",
"'Don't Know Why' by Norah Jones",
"'Don't Let Me Be Lonely Tonight' by James Taylor",
"'Don't Speak' by No Doubt",
"'Don't Stop Believin' (Regionals version)' by Glee Cast",
"'Don't Wanna Fight' by Alabama Shakes",
"'Don't You Wanna Stay' by Jason Aldean with Kelly Clarkson",
"'Doo Wop (That Thing)' by Lauryn Hill",
"'Drink in My Hand' by Eric Church",
"'Drops of Jupiter (Tell Me)' by Train",
"'Drunk in Love' by Beyoncé featuring Jay Z",
"'E-Pro' by Beck",
"'Everybody (Backstreet's Back)' by Backstreet Boys",
"'Everyday Is a Winding Road' by Sheryl Crow",
"'Fallin' for You' by Colbie Caillat",
"'Fallin'' by Alicia Keys",
"'Fancy' by Iggy Azalea featuring Charli XCX",
"'Feel Good Inc.' by Gorillaz, De La Soul",
"'Fill Me In' by Craig David",
"'Fine Line' by Paul McCartney",
"'Firework' by Katy Perry",
"'Foolish' by Ashanti",
"'Forget You' by Cee Lo Green",
"'Fragile' by Sting",
"'Freedom at 21' by Jack White",
"'From the Bottom of My Heart' by Stevie Wonder",
"'Gangsta's Paradise' by Coolio, L.V.",
"'Genie in a Bottle' by Christina Aguilera",
"'Gentle on My Mind' by The Band Perry",
"'Get Lucky' by Daft Punk featuring Pharrell Williams",
"'Get Out of This House' by Shawn Colvin",
"'Get the Party Started' by Pink",
"'Gimme the Light' by Sean Paul",
"'Girl All the Bad Guys Want' by Bowling for Soup",
"'Girl Crush' by Little Big Town",
"'Girlfriend' by *NSYNC",
"'Give Me One Reason' by Tracy Chapman",
"'Going On' by Gnarls Barkley",
"'Going Under' by Evanescence",
"'Good Is Good' by Sheryl Crow",
"'Good Life' by Kanye West featuring T-Pain",
"'Good Vibrations' by Brian Wilson",
"'Got Money' by Lil Wayne featuring T-Pain",
"'Grenade' by Bruno Mars",
"'Half of My Heart' by John Mayer with Taylor Swift",
"'Halo' by Beyoncé",
"'Happy (Live)' by Pharrell Williams",
"'Haven't Met You Yet' by Michael Bublé",
"'He Thinks He'll Keep Her' by Mary Chapin Carpenter",
"'Heaven' by Los Lonely Boys",
"'Hello' by Adele",
"'Here Comes Goodbye' by Rascal Flatts",
"'Here We Go Again' by Ray Charles and Norah Jones",
"'Hero' by Mariah Carey",
"'Hey There Delilah' by Plain White T's",
"'Hey, Soul Sister (live)' by Train",
"'Hide and Seek' by Imogen Heap",
"'Highway Don't Care' by Tim McGraw featuring Taylor Swift and Keith Urban",
"'Ho Hey' by The Lumineers",
"'Hold Back the River' by James Bay",
"'Hold On' by Alabama Shakes",
"'Hole in the World' by Eagles",
"'Holocene' by Bon Iver",
"'Hometown Glory' by Adele",
"'Honest with Me' by Bob Dylan",
"'Honey Bee' by Blake Shelton",
"'Hot in Herre' by Nelly",
"'Hot n Cold' by Katy Perry",
"'Hotline Bling' by Drake",
"'House of Cards' by Radiohead",
"'How You Remind Me' by Nickelback",
"'Humble and Kind' by Tim McGraw",
"'I Am a Man of Constant Sorrow' by The Soggy Bottom Boys",
"'I Believe I Can Fly' by R. Kelly",
"'I Can Love You Like That' by All-4-One",
"'I Gotta Feeling' by The Black Eyed Peas",
"'I Kissed a Girl' by Katy Perry",
"'I Need to Know' by Marc Anthony",
"'I Run to You' by Lady Antebellum",
"'I Try' by Macy Gray",
"'I Want It That Way' by Backstreet Boys",
"'I Want Love' by Elton John",
"'I Will Follow You into the Dark' by Death Cab for Cutie",
"'I Will Wait' by Mumford & Sons",
"'I Wish I Wasn't' by Heather Headley",
"'I'll Go Crazy If I Don't Go Crazy Tonight' by U2",
"'I'll Make Love to You' by Boyz II Men",
"'I'm Like a Bird' by Nelly Furtado",
"'I'm with You' by Avril Lavigne",
"'Icky Thump' by The White Stripes",
"'If Everyone Cared' by Nickelback",
"'If I Ain't Got You' by Alicia Keys",
"'If I Die Young' by The Band Perry",
"'Imitation of Life' by R.E.M.",
"'In da Club' by 50 Cent",
"'Instant Karma!' by U2",
"'Iris' by Goo Goo Dolls",
"'Ironic' by Alanis Morissette",
"'Irreplaceable' by Beyoncé",
"'Is It Any Wonder?' by Keane",
"'It Happens' by Sugarland",
"'It Hurt So Bad' by Susan Tedeschi",
"'It's like That' by Mariah Carey featuring Jermaine Dupri and Fatman Scoop",
"'It's Not Over' by Daughtry",
"'Jenny Wren' by Paul McCartney",
"'Jesus, Take the Wheel' by Carrie Underwood",
"'John Cougar, John Deere, John 3:16' by Keith Urban",
"'Just a Kiss' by Lady Antebellum",
"'Just Give Me a Reason' by Pink featuring Nate Ruess",
"'Just the Way You Are' by Bruno Mars",
"'Keep Me in Your Heart' by Warren Zevon",
"'Kiss from a Rose' by Seal",
"'Landslide' by Dixie Chicks",
"'Lego House' by Ed Sheeran",
"'Let Her Cry' by Hootie & the Blowfish",
"'Let's Get It Started' by The Black Eyed Peas",
"'Life in Technicolor II' by Coldplay",
"'Like a Star' by Corinne Bailey Rae",
"'Lips Are Movin' by Meghan Trainor",
"'Little Toy Guns' by Carrie Underwood",
"'Livin' la Vida Loca' by Ricky Martin",
"'Locked Out of Heaven' by Bruno Mars",
"'Lonely Boy' by The Black Keys",
"'Lonely No More' by Rob Thomas",
"'Longing in Their Hearts' by Bonnie Raitt",
"'Lose Yourself' by Eminem",
"'Love Can Go to Hell' by Brandy Clark",
"'Love Don't Live Here' by Lady Antebellum",
"'Love Sneakin' Up On You' by Bonnie Raitt",
"'Love Song' by Sara Bareilles",
"'Love the One You're With' by Luther Vandross",
"'Love the Way You Lie' by Eminem featuring Rihanna",
"'Love Yourself' by Justin Bieber",
"'Love's Divine' by Seal",
"'Lullaby' by Shawn Mullins",
"'Madness' by Muse",
"'Makes Me Wonder' by Maroon 5",
"'Mambo No. 5 (A Little Bit Of...)' by Lou Bega",
"'Mean' by Taylor Swift",
"'Meanwhile Back at Mama's' by Tim McGraw featuring Faith Hill",
"'Mercy' by Duffy",
"'Merry Go 'Round' by Kacey Musgraves",
"'Mine Would Be You' by Blake Shelton",
"'Mirrors' by Justin Timberlake",
"'Misery' by Maroon 5",
"'MMMBop' by Hanson",
"'Monkey to Man' by Elvis Costello & The Imposters",
"'Moves like Jagger' by Maroon 5 featuring Christina Aguilera",
"'Ms. Jackson' by OutKast",
"'Music' by Madonna",
"'My Baby' by LeAnn Rimes",
"'My Church' by Maren Morris",
"'My Father's Eyes' by Eric Clapton",
"'My Heart Will Go On' by Celine Dion",
"'My Humps' by The Black Eyed Peas",
"'My Immortal' by Evanescence",
"'My Life Would Suck Without You' by Kelly Clarkson",
"'Need U Bad' by Jazmine Sullivan featuring Missy Elliott",
"'Need You Now' by Lady Antebellum",
"'No Scrubs' by TLC",
"'Nobody Knows' by The Tony Rich Project",
"'Not Ready to Make Nice' by Dixie Chicks",
"'Nothin' on You' by B.o.B featuring Bruno Mars",
"'October Road' by James Taylor",
"'On & On' by Erykah Badu",
"'One of Us' by Joan Osborne",
"'One Sweet Day' by Mariah Carey & Boyz II Men",
"'Oops!... I Did It Again' by Britney Spears",
"'Optimistic' by Radiohead",
"'Ordinary Miracles' by Barbra Streisand",
"'Ordinary People' by John Legend",
"'Over My Head (Cable Car)' by The Fray",
"'Overprotected' by Britney Spears",
"'Paper Planes' by M.I.A.",
"'Paradise' by Coldplay",
"'Payphone' by Maroon 5 featuring Wiz Khalifa",
"'Pedestrian at Best' by Courtney Barnett",
"'Peter Pan' by Kelsea Ballerini",
"'Piece By Piece (Idol Version)' by Kelly Clarkson",
"'Pinch Me' by Barenaked Ladies",
"'Please Read the Letter' by Robert Plant and Alison Krauss",
"'Poker Face' by Lady Gaga",
"'Prayer for the Dying' by Seal",
"'Problem' by Ariana Grande featuring Iggy Azalea",
"'Pumped Up Kicks' by Foster the People",
"'Put Your Records On' by Corinne Bailey Rae",
"'Pyramids' by Frank Ocean",
"'Radioactive' by Imagine Dragons",
"'Rain Fall Down' by The Rolling Stones",
"'Raise 'Em Up' by Keith Urban featuring Eric Church",
"'Ray of Light' by Madonna",
"'Reach' by Gloria Estefan",
"'Ready to Start' by Arcade Fire",
"'Really Love' by D'Angelo and the Vanguard",
"'Redneck Woman' by Gretchen Wilson",
"'Rehab' by Amy Winehouse",
"'Retrograde' by James Blake",
"'River' by Herbie Hancock featuring Corinne Bailey Rae",
"'Roar' by Katy Perry",
"'Rolling in the Deep' by Adele",
"'Royals' by Lorde",
"'Said I Loved You...But I Lied' by Michael Bolton",
"'Same Love' by Macklemore and Ryan Lewis featuring Mary Lambert",
"'Save Me' by Aimee Mann",
"'Save Room' by John Legend",
"'Save Tonight' by Eagle-Eye Cherry",
"'Say It Right' by Nelly Furtado",
"'Say My Name' by Destiny's Child",
"'Scary Monsters and Nice Sprites' by Skrillex",
"'See You Again (from Furious 7)' by Wiz Khalifa featuring Charlie Puth",
"'Send Your Love' by Sting",
"'Set Fire to the Rain (Live)' by Adele",
"'Sexx Laws' by Beck",
"'SexyBack' by Justin Timberlake",
"'Shake It Off' by Taylor Swift",
"'Shake It Out' by Florence and the Machine",
"'Shape of My Heart' by Backstreet Boys",
"'She Will Be Loved' by Maroon 5",
"'Ship to Wreck' by Florence and the Machine",
"'Should've Been Us' by Tori Kelly",
"'Show Me the Meaning of Being Lonely' by Backstreet Boys",
"'Silver Springs' by Fleetwood Mac",
"'Since U Been Gone' by Kelly Clarkson",
"'Sing' by Ed Sheeran",
"'Sitting, Waiting, Wishing' by Jack Johnson",
"'Smooth' by Santana featuring Rob Thomas",
"'So What' by Pink",
"'Soak Up the Sun' by Sheryl Crow",
"'Sober' by Pink",
"'Sogno' by Andrea Bocelli",
"'Somebody That I Used to Know' by Gotye featuring Kimbra",
"'Somethin' Bad' by Miranda Lambert with Carrie Underwood",
"'Soul Meets Body' by Death Cab for Cutie",
"'Speed of Sound' by Coldplay",
"'Spiderwebs' by No Doubt",
"'Stacy's Mom' by Fountains of Wayne",
"'Stay with Me (Darkchild Version)' by Sam Smith",
"'Stickwitu' by The Pussycat Dolls",
"'Still' by Brian McKnight",
"'Streets of Philadelphia' by Bruce Springsteen",
"'Stressed Out' by Twenty One Pilots",
"'Stronger (What Doesn't Kill You)' by Kelly Clarkson",
"'Stupid Girl' by Garbage",
"'Stupid Girls' by Pink",
"'Sugar' by Maroon 5",
"'Sunny Came Home' by Shawn Colvin",
"'Sunrise' by Norah Jones",
"'Super Bass' by Nicki Minaj",
"'Superman (It's Not Easy)' by Five for Fighting",
"'Swimming Pools (Drank)' by Kendrick Lamar",
"'Take a Little Ride' by Jason Aldean",
"'Take Me to Church' by Hozier",
"'Take Your Time' by Sam Hunt",
"'Telephone' by Lady Gaga featuring Beyoncé",
"'The A Team' by Ed Sheeran",
"'The Boy Is Mine' by Brandy, Monica",
"'The Cave' by Mumford & Sons",
"'The First Cut Is the Deepest' by Sheryl Crow",
"'The House That Built Me' by Miranda Lambert",
"'The Only Exception' by Paramore",
"'The Painter' by Neil Young",
"'The Power of Love' by Celine Dion",
"'The Pretender' by Foo Fighters",
"'The Real Slim Shady' by Eminem",
"'The Way You Move' by OutKast featuring Sleepy Brown",
"'Thinking Out Loud' by Ed Sheeran",
"'This Is It' by Michael Jackson",
"'Through the Wire' by Kanye West",
"'Torn' by Natalie Imbruglia",
"'Traveller' by Chris Stapleton",
"'Try' by Pink",
"'Un-Break My Heart' by Toni Braxton",
"'Unwell' by Matchbox Twenty",
"'Unwritten' by Natasha Bedingfield",
"'Uptown Funk' by Mark Ronson featuring Bruno Mars",
"'Use Somebody' by Kings of Leon",
"'Vertigo' by U2",
"'Vice' by Miranda Lambert",
"'Video' by India.Arie",
"'Virtual Insanity' by Jamiroquai",
"'Viva la Vida' by Coldplay",
"'Waiting in the Weeds' by Eagles",
"'Waiting on the World to Change' by John Mayer",
"'Walk On By' by Seal",
"'Walk On' by U2",
"'Walk' by Foo Fighters",
"'Wanted' by Hunter Hayes",
"'Waterfalls' by TLC",
"'We Are Never Ever Getting Back Together' by Taylor Swift",
"'We Are Young' by Fun featuring Janelle Monáe",
"'We Take Care of Our Own' by Bruce Springsteen",
"'What a Girl Wants' by Christina Aguilera",
"'What Goes Around.../...Comes Around' by Justin Timberlake",
"'What You Give Away' by Vince Gill and Sheryl Crow",
"'What's My Name?' by Rihanna featuring Drake",
"'Whataya Want from Me' by Adam Lambert",
"'Where Are You Going' by Dave Matthews Band",
"'Where Have All the Cowboys Gone?' by Paula Cole",
"'Where Is the Love?' by The Black Eyed Peas featuring Justin Timberlake",
"'Who Will Save Your Soul' by Jewel",
"'Wide Awake' by Katy Perry",
"'Wide Open Spaces' by Dixie Chicks",
"'Without Me' by Eminem",
"'Won't Go Home Without You' by Maroon 5",
"'Work It' by Missy Elliott",
"'Work Out' by J. Cole",
"'Working Class Hero' by Green Day",
"'Wrecking Ball' by Miley Cyrus",
"'You and I' by Lady Gaga",
"'You and Me' by Dave Matthews Band",
"'You Are Not Alone' by Michael Jackson",
"'You Belong with Me' by Taylor Swift",
"'You Can Close Your Eyes' by Sheryl Crow",
"'You Found Me' by The Fray",
"'You Had Me' by Joss Stone",
"'You Oughta Know' by Alanis Morissette",
"'You Raise Me Up' by Josh Groban",
"'You Rock My World' by Michael Jackson",
"'You Were Meant for Me' by Sting",
"'You're Beautiful' by James Blunt",
"'You're Still the One' by Shania Twain",
"'You're the One' by Paul Simon",
"'Your Body Is a Wonderland' by John Mayer"

]
